### ISSUE TITLE
EM2 Wii U/PS3 Support?

### ISSUE THREAD

**Issue by SirGamers** [KjubDusJub/Epic-Mickey-Launcher#7]
I mean they both have Emulators ([Cemu](https://cemu.info/) and [RPCS3](https://rpcs3.net/)) that are pretty stable.
the compatibility is good for [Cemu](https://wiki.cemu.info/wiki/Disney_Epic_Mickey_2:_The_Power_of_Two) and ditto for [RPCS3](https://rpcs3.net/compatibility?g=epic+mickey#jump)
idk about xbox 360 tho because i don't think [xenia](https://xenia.jp/) is stable enough (yet)
what do you think?

**Comment by kalsvik** [comment]
While I have toyed around with the idea of adding support for Wii U, PS3, and maybe even XBOX, I've never really felt motivated to go through with it since I can't see anyone actually requiring support for it. That being said, I do eventually want to add support for every possible version of Epic Mickey, including POI, so this will eventually be added. I will keep this issue open if anyone else would like to add some input.
