### ISSUE TITLE
Automatically Download & Assign options grayed out on OSX

### ISSUE THREAD

**Issue by kungpowell** [KjubDusJub/Epic-Mickey-Launcher#9]
I'm running Sonoma 14.4. If this is not an option for Mac, what are the instructions for manually assigning the paths.  

Thank so much for all you work on this!

**Comment by kalsvik** [comment]
Currently, the automatic ISO extraction method is based on Windows-only tools since I haven't bothered writing my own ISO extractor (I have no idea how to). Because Wine on Linux is quite mature and works quite well, it is actually possible to set it up there, and considering macOS is also based on UNIX, it is probably possible to make it work there, too. However, because developing software for macOS is absolute hell, I haven't tried to make it work yet. It's definitely on my list of things to add, but the priority isn't high, considering the amount of EML users who actually use macOS.

There is a solution, however:
If you manually download Dolphin from [this website](https://nb.dolphin-emu.org/) and add the game you want to its game list, you can extract the game that way.

Here's a guide on how to extract games with Dolphin: https://www.youtube.com/watch?v=plUi3Ak-B98

I'll keep this issue open until I eventually add this.

**Comment by kungpowell** [comment]
Thanks for the response, KjubDusJub. This is helpful, but I was looking for how to manually assign the WIT Path and Nkit Path. That's what seems to be missing. But I understand spending time on Mac issues is not the top priority,. I'll keep looking for a solution. Best of luck with EML!

**Comment by kalsvik** [comment]
Unfortunately, WIT and NKit don't work with macOS.
You will have to extract your game with Dolphin.
You can assign Dolphin to EML by pressing the assign button for it and selecting the dolphin .app (usually in your Applications folder)

**Comment by kungpowell** [comment]
Again, thank you!

**Comment by kalsvik** [comment]
In a weird turn of events, mostly because I was inspired by this thread to get ISO extraction to work everywhere, I've forked Dolphin and implemented iso extraction from a place EML can access it. This not only means that there's only one prerequisite that you need to install, but it also means that EML is now fully native on all platforms (Windows/Linux/Mac), which means if you download the [latest version](https://github.com/KjubDusJub/Epic-Mickey-Launcher/releases/tag/0.4.4) you should be able to just install the dolphin fork (which you can do in the Settings tab) and then add the game like you would normally anywhere else. (:

**Comment by kungpowell** [comment]
This is great! I so appreciate the extra work to make this happen. Thank you!
